version: '3.6'

services:
  fms:
    restart: always
    image: ${APP_IMAGE_NAME}:${APP_IMAGE_VERSION}
    container_name: ${CONTAINER_NAME}
    ports:
      - ${APP_PORT}:3020
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${VOLUME_EI}:${VOLUME_EI}:ro
    command: yarn start


networks:
  default:
    external:
      name: prod
